# ファイル名: docker/docker-compose.dokploy.yaml
services:
  nginx:
    # DokployのTraefikと競合しないよう、ホスト公開を消す
    ports: null
    # コンテナ内80番だけ見せる
    expose:
      - "80"
    networks:
      - default
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - 'traefik.http.routers.dify.rule=Host(`dify.hyper-typer.xyz`)'
      - "traefik.http.routers.dify.entrypoints=web"
      - "traefik.http.services.dify.loadbalancer.server.port=80"
      - "traefik.docker.network=dokploy-network"

networks:
  dokploy-network:
    external: true
